### ISSUE TITLE
Buf.list is actually using a Blob

### ISSUE THREAD

**Issue by JJ** [Raku/roast#526]
This line:
https://github.com/perl6/roast/blob/c91e423a9ae8afd7026a8471269013e375d10a62/S32-str/encode.t#L63

Is using a Blob[uint8], not a Buf:

    say "zipi".encode("ascii").^name; # OUTPUT: «Blob[uint8]␤»

**Comment by lizmat** [comment]
I'm not sure what the problem is?

**Comment by JJ** [comment]
Shouldn't it be testing an actual Buf? The implementation of Buf.list is
different from Blob.list, far as I can tell: https://github.com/rake
udo/rakudo/blob/master/src/core/Buf.pm6#L330 This is the one for Blob, for
instance. The one for Buf is not tested, I think.

**Comment by lizmat** [comment]
Good catch!
