### ISSUE TITLE
Roast depends on Rakudo when it shouldn't

### ISSUE THREAD

**Issue by niner** [Raku/roast#640]
Checking out roast and running `perl fudgeandrun $(sed 's/#.*//' spectest.data | grep '\.t')` using the system wide installed rakudo master yields the following test failures:
```
[ 1809s] Test Summary Report
[ 1809s] -------------------
[ 1809s] S03-metaops/misc.t                                       (Wstat: 256 Tests: 0 Failed: 0)
[ 1809s]   Non-zero exit status: 1
[ 1809s]   Parse errors: No plan found in TAP output
[ 1809s] S26-documentation/block-leading-user-format.t            (Wstat: 256 Tests: 0 Failed: 0)
[ 1809s]   Non-zero exit status: 1
[ 1809s]   Parse errors: No plan found in TAP output
[ 1809s] integration/advent2010-day03.t                           (Wstat: 512 Tests: 2 Failed: 2)
[ 1809s]   Failed tests:  1-2
[ 1809s]   Non-zero exit status: 2
[ 1809s]   Parse errors: Bad plan.  You planned 12 tests but ran 2.
[ 1809s] Files=1361, Tests=188669, 1777 wallclock secs (24.89 usr  2.58 sys + 2077.74 cusr 109.43 csys = 2214.64 CPU)
[ 1809s] Result: FAIL
```

`S03-metaops/misc.t` and `S26-documentation/block-leading-user-format.t` fail because they try to load a module called `Test::Helpers` which seems to be part of rakudo's tests. `integration/advent2010-day03.t` fails because it expects the files `Makefile CREDITS LICENSE README.md` which are clearly part of rakudo and not roast.

This is blocking automated spectests for every rakudo commit on the Open Build Service.

**Comment by niner** [comment]
`S03-metaops/misc.t` was easy to fix. Done so in commit c2666ff0c346e150cefc3b108aa7d2930f76e7b4

**Comment by JJ** [comment]
From Test::Helpers apparently what's used is `is-run`. Could probably be ported to the file itself, since it's not used from anywhere else. Let me try that.

**Comment by JJ** [comment]
Reopening because there are still problems with `integration/advent2010-day03.t` Sorry about that.

**Comment by JJ** [comment]
This last one is probably redundant, since it's actually testing `dir`, which is tested elsewhere. Optionally, we can simply test other files.

**Comment by ugexe** [comment]
Test::Helpers is part of roast -- https://github.com/Raku/roast/tree/master/packages/Test-Helpers

**Comment by niner** [comment]
On Sonntag, 10. Mai 2020 18:14:45 CEST Nick Logan wrote:
> Test::Helpers is part of roast --

Yes and no. Roast contains a Test::Helpers distribution but that's an entirely 
different thing from the Test::Helpers module in Rakudo's t/lib

**Comment by ugexe** [comment]
> Yes and no. Roast contains a Test::Helpers distribution but that's an entirely
different thing from the Test::Helpers module in Rakudo's t/lib

Ah. Then sounds like they should use https://github.com/Raku/roast/blob/6d23891a3a7e38ebdd0d6ec6b7c79a83a35c7445/packages/Test-Helpers/lib/Test/Util.pm6#L107
