### ISSUE TITLE
&sigiled Callable in where clause not covered

### ISSUE THREAD

**Issue by gfldex** [Raku/roast#650]
```
my &block = { False }; sub s($a where &block) { say $a }; s 'OK';
sub check { False }; sub s($a where &check) { say $a }; s 'OK'
```
Both cases are supported by Rakudo but are not checked for in the spec.
discussion: https://colabti.org/irclogger/irclogger_log/raku-dev?date=2020-06-26#l31

**Comment by vrurg** [comment]
Can you submit a PR? Apparently, `where` accepting a block assumes it would accept a routine too. But a test of this kind could be useful in catching unforseen side effects of some future commits.
