### ISSUE TITLE
Remove rosettacode tests

### ISSUE THREAD

**Issue by coke** [Raku/roast#651]
These were added pre-6.c as a way to ensure that changes to Raku didn't break the examples on rosettacode - but this isn't the right repository for that sort of test. Only 2 tests were ever added anyway.

They got grandfathered into the spec in the Christmas release of 2015

```
t/spec/rosettacode/greatest_element_of_a_list.t ................... ok
t/spec/rosettacode/sierpinski_triangle.t .......................... ok
```

**Comment by vrurg** [comment]
What harm doesn't do to have them in there? The general idea of not breaking the examples published at one of the greatest sources of code snippets appeals to me as a good one.

And if not in roast where then? Though quick thinking brings an idea of a dedicated module which would be tested with Blin once in a while.

**Comment by coke** [comment]
Harm? If it's not spec, it doesn't belong.

Not breaking the examples is a good goal, but it's not the goal of roast.

Ingy had some work in this direction (https://github.com/ingydotnet/rosettacode-pm).

**Comment by thundergnat** [comment]
I don't have a horse in this race, it doesn't much matter to me if the existing Rosettacode tests stay in roast or not. I can see the argument either way.

Just as a point of reference, github user [SqrtNegInf](https://github.com/SqrtNegInf) (not me) does a daily test run of the entire[*] Rosettacode Raku corpus on a current build of master. See: https://github.com/SqrtNegInf/Rosettacode-Perl6-Smoke 

It isn't under direct community control, but he is pretty proactive about finding and reporting bugs that appear, so removing the tests from roast won't mean it doesn't get tested.

[*] ok, _entire_ may be a stretch... more like about 90-95%; everything that can be run hands off and programmatically compared to expected output.

**Comment by vrurg** [comment]
@thundergnat Thanks for pointing at @SqrtNegInf project. I asked if he can turn his project into a testable module we can then test with Blin.
