### ISSUE TITLE
spectest.data in roast needs some updates

### ISSUE THREAD

**Issue by coke** [Raku/roast#654]
* should mention that is used currently by Rakudo but can be adapted for other implementations
* any rakudo-specific elements (like "make quicktest") should be called out as rakudo-specific.
* Remove RT references - describe where tickets should be opened (roast/rakudo/problem-solving)
* Do we have a document on fudging? the paragraph here could be replaced to a more complete doc.

**Comment by vrurg** [comment]
What an Augean stables have you just touched!.. 

>     * should mention that is used currently by Rakudo but can be adapted for other implementations

This is defined in README.md. We don't need to mention Rakudo whatsoever.

>     * any rakudo-specific elements (like "make quicktest") should be called out as rakudo-specific.

They should be removed or rather moved into Rakudo Makefile.

>     * Remove RT references - describe where tickets should be opened (roast/rakudo/problem-solving)

Only roast or problem-solving. Rakudo repo is for implementation errors.

>     * Do we have a document on fudging? the paragraph here could be replaced to a more complete doc.

README.md has it.

Similar changes need to be done to the tools too.

**Comment by vrurg** [comment]
@coke Thanks! Few more things were done along the way of fixing `spectest.data`. :)
