### ISSUE TITLE
If print "T" for ^4 works to print TTTT, why can't print "T" * 4 multiply T the same?

### ISSUE THREAD

**Issue by marek-lach** [Raku/roast#776]
I understand the compiler error states `Cannot convert string to number`. Is this because mathematical operators (like `*`) automatically indicate that the input given `("T")` is/must always only be a number?

Is there a technical/design limitation to why can't it also print a `string`, if given a string in quote marks as an input to process (multiply here)?

Thanks,
M

**Comment by vendethiel** [comment]
You can use the `x` operator for string repetition.

**Comment by colomon** [comment]
Just to clarify lizmat's examples a bit:

`say "42" * "4" # 168`

and

`say 42 x "4" # 42424242`

That is to say, `*` wants two numbers, and 'x' wants a string and a number.  Both will try to convert arguments to what they want.
