### ISSUE TITLE
Promote DEPRECATE

### ISSUE THREAD

**Issue by 0rir** [Raku/roast#826]
`Perl6::World::DEPRECATED` is in 'user' code on github.   This offers Raku users more facility than  `is DEPRECATED` by allowing the deprecation-version, elimination-version, and the alternative.

There is no apparent reason that deprecation should be constrained to OO code.  And in OO, the direct use of  `DEPRECATED`  in `Callable`s  can look convenient and clear.

Please promote `DEPRECATED` from an implementation detail to a roasted item.

**Comment by JJ** [comment]
Sorry, why is this issue in this repo? Wouldn't either problem-solving or the Rakudo repo itself be a better venue for it?

**Comment by 0rir** [comment]
In my previous,  `DEPRECATE` should be `DEPRECATED` in every instance. And profiling shows I found the wrong  method, the work is done by `Rakudo::Deprecations::DEPRECATED`.  Edits made.

Thanks, @JJ.

I am asking that `DEPRECATED`'s use beyond `is DEPRECATED` be specified as part of Raku.  That usage being like this:
```
#!/usr/bin/env raku
sub d(--> Str) {
    DEPRECATED(  'Use-me', 'Since', 'Gone', :what('sub d') );           
    'd';
}
d();
```

**Comment by JJ** [comment]
In that case, I thing `problem-solving` is the right venue; it's where new features are proposed and discussed. I can move the issue there if you want.

**Comment by 0rir** [comment]
@JJ, Thank for the education.  I'll close here, clean up and move it.
